### ISSUE TITLE
Bug: vars definition in route - lint and sync not working

### ISSUE THREAD

**Issue by nagarajusunkara** [api7/adc#166]
### Current Behavior

When I run `adc lint ` for below route it fails saying
```yaml
services:
  - name: home-cq-service
    labels:
      DEMO: CQ
    upstream:
      pass_host: pass
      nodes:
        - host: apache-cq.content
          port: 80
          weight: 1
          priority: 0
      type: roundrobin
      scheme: http
      name: home-cq-upstream
      keepalive_pool:
        requests: 1000
        idle_timeout: 60
        size: 320
      hash_on: vars
      timeout:
        send: 30
        read: 60
        connect: 2
    routes:
      - name: home-route
        description: "Home Page"
        labels:
          DEMO: CQ
        hosts:
          - "qa1.demo.com"
        uris:
          - /
        priority: 0
        vars:
          - - 'cookie_store'
            - '=='
            - 'travel'
        plugins:
          redirect:
            ret_code: 301
            uri: https://$host/us/en/home.html
```

i got the below error
The following errors were found in configuration:
Invalid input at service: "home-cq-service", field: "routes.1.vars.0"

    at Task.task [as taskFn] (dist/apps/cli/main.js:93805:19)
    at Task.run (dist/apps/cli/main.js:28612:35)

### Exxpected Behavior

It should pass all validations

### Steps to Reproduce

1. run `adc lint --file <yaml provided above>`

### Environment

- APISIX version: 3.9.1
- ADC version (run `adc version`): 0.12.0
- Operating system (run `uname -a`): Darwin IBBL-ADRDWS 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64
