### ISSUE TITLE
Feature: route to different service

### ISSUE THREAD

**Issue by artworkad** [api7/adc#181]
### Description

With regular apisix structure I can assign a service to a route, while with adc I have to put the routes under a service. That leads to the problem, that I cannot send the request to a different upstream. 

E.g.

```
services:
- name: a
  ..
- name: b
  ..
  routes:
    - uris:
      - /do
      priority: 1
      methods:
        - POST
    - uris:
      - /do
      methods:
        - POST
      priority: 2
      service: a
      filter_func: > 
       ...
```

The /do route with prio 2 should go to a different upstream/service. That's a common scenario where you migrate an old api step by step to a new one. The current [schema ](https://github.com/api7/adc/blob/c428eea536763d7e271a4a953c791c0530cd7679/schema.json) does not support that, or am I missing something?

Thanks in advance!

**Comment by pottekkat** [comment]
@artworkad You would have to create a different service if the routes should be to different upstreams. The API7 Enterprise (Enterprise APISIX) supports this new schema.

I do believe the above way is quite easy to follow.

However, if you do wish to follow your current configuration style, you can use the `--no-lint` flag with the sync command which will sync your configuration file as it is. Since APISIX supports the old way of configuring different upstreams to different routes within a service, the configuration will work but you will bypass the ADC-side validation.

Does that help?

**Comment by artworkad** [comment]
@pottekkat thanks! Based on your explanation I introduced a third service `a-to-b`, which will be exposed via api `a` and internally route to `b`. It's working fine:

```
services:
- name: a-to-b
  ...
  upstream:
     b
  hosts:
    - a.api.example.com
  routes:
    - uris:
      - /do
      methods:
        - POST
      priority: 2
      filter_func: > 
        ...
      plugins:
        proxy-rewrite:
          host: b.api.example.com
          uri: ...
- name: a
  upstream:
     a
  hosts:
    - a.api.example.com
  routes:
    - uris:
      - /do
      priority: 1
      methods:
        - POST
- name: b
  upstream:
     b
  hosts:
    - b.api.example.com
  routes:
    ...
```

I like the approch. Initially I thought there should only be one service per upstream. Will apisix eventually adopt this new schema?
