### ISSUE TITLE
bug: environment variables in YAML don't parse properly as non-string types

### ISSUE THREAD

**Issue by cverdela** [api7/adc#243]
### Current Behavior

Expected number, received string at service: "PO", field: "upstream.nodes.0.port"

### Exxpected Behavior

success

### Steps to Reproduce

相关配置文件如下
```
services:
  - name: PO
    id: PO
    upstream:
      type: roundrobin
      pass_host: pass
      nodes:
        - host: ${PO_Host}
          port: ${PO_Port}
          weight: 1
          priority: 0
      scheme: http
      hash_on: vars
      name: PO
```
.env中环境变量如下：
PO_Port=3232

### Environment

- ADC version (run `adc version`):0.16.1
