### ISSUE TITLE
Bug: adc lint 将形如 `8e287857 ` 这样的 id 识别为数字

### ISSUE THREAD

**Issue by dspo** [api7/adc#257]
### Current Behavior

配置示例：
```yaml
services:
  - id: 8e287857
     hosts:
      - httpbin.example
...
```

adc lint 结果：
```log
The following errors were found in configuration:
#1 Expected string, received number at service: "xxx", field: "id"
```

adc 将 `id: 8e287857` 当作了数字。
不确定是否符合预期。目前我们规避这种情况在做法是使用 json 而不是 yaml。

### Environment

- APISIX version:
- ADC version (run `adc version`): 0.19.0 等多个版本
- Operating system (run `uname -a`):
