### ISSUE TITLE
Bug: Unable to sync config with label-selectors

### ISSUE THREAD

**Issue by hebbaa** [api7/adc#263]
### Current Behavior

Have below config in file **config.yaml** 

```yaml
services:
  - name: mockbin Service
    labels:
      deployment: staging
    upstream:
      name: Default Upstream
      scheme: http
      type: roundrobin
      hash_on: vars
      nodes:
        - host: mock.api7.ai
          port: 80
          weight: 100
          priority: 0
      timeout:
        connect: 60
        send: 60
        read: 60
      retry_timeout: 0
      keepalive_pool:
        size: 320
        idle_timeout: 60
        requests: 1000
      pass_host: pass
    strip_path_prefix: true
```

When i try to sync this config with command 

`adc sync -f config.yaml --label-selector  deployment=staging`

Getting below error 
```
[7:03:06 AM] [ADC] › ▶  start     Load local configuration
[7:03:06 AM] [ADC] › ▶  start     Load /config.yaml
[7:03:06 AM] [ADC] › ✔  success   Load /config.yaml
[7:03:06 AM] [ADC] › ▶  start     Merge local configurations
[7:03:06 AM] [ADC] › ✔  success   Merge local configurations
[7:03:06 AM] [ADC] › ▶  start     Resolve value variables
[7:03:06 AM] [ADC] › ✔  success   Resolve value variables
[7:03:06 AM] [ADC] › ▶  start     Filter configuration
[7:03:06 AM] [ADC] › ✔  success   Filter configuration
[7:03:06 AM] [ADC] › ✔  success   Load local configuration
[7:03:06 AM] [ADC] › ▶  start     Lint configuration
[7:03:06 AM] [ADC] › ✔  success   Lint configuration
[7:03:06 AM] [ADC] › ▶  start     Load remote configuration
[7:03:06 AM] [ADC] › ▶  start     Fetch all configuration
[7:03:06 AM] [APISIX] › ▶  start     Fetch services
[7:03:06 AM] [APISIX] › ✔  success   Fetch services
[7:03:06 AM] [APISIX] › ▶  start     Fetch stream_routes
[7:03:06 AM] [APISIX] › ✔  success   Fetch stream_routes
[7:03:06 AM] [APISIX] › ▶  start     Fetch routes
[7:03:06 AM] [APISIX] › ✔  success   Fetch routes
[7:03:06 AM] [APISIX] › ▶  start     Fetch plugin_configs
[7:03:06 AM] [APISIX] › ✔  success   Fetch plugin_configs
[7:03:06 AM] [APISIX] › ▶  start     Fetch ssls
[7:03:06 AM] [APISIX] › ✔  success   Fetch ssls
[7:03:06 AM] [APISIX] › ▶  start     Fetch plugin_metadata
[7:03:06 AM] [APISIX] › ✔  success   Fetch plugin_metadata
[7:03:06 AM] [APISIX] › ▶  start     Fetch consumers
[7:03:06 AM] [APISIX] › ✔  success   Fetch consumers
[7:03:06 AM] [APISIX] › ▶  start     Fetch upstreams
[7:03:06 AM] [APISIX] › ✔  success   Fetch upstreams
[7:03:06 AM] [APISIX] › ▶  start     Fetch global_rules
[7:03:06 AM] [APISIX] › ✔  success   Fetch global_rules
[7:03:06 AM] [ADC] › ✔  success   Fetch all configuration
[7:03:06 AM] [ADC] › ▶  start     Filter remote configuration
[7:03:06 AM] [ADC] › ✖  error     Filter remote configuration
[7:03:06 AM] [ADC] › ✖  error     Load remote configuration
[7:03:06 AM] [ADC] › ✖  fatal     TypeError: Cannot assign to read only property 'ssls' of object '#<Object>' 
    at dist/apps/cli/main.js:89258:37
    at Array.forEach (<anonymous>)
    at filterConfiguration (dist/apps/cli/main.js:89254:32)
    at Task.task [as taskFn] (dist/apps/cli/main.js:102260:68)
    at Task.run (dist/apps/cli/main.js:37469:35)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

adc --version
0.19.0

apisix version:
3.9.0

environment:
Kubernetes 

### Exxpected Behavior

The configuration should have synced with backend. 

### Steps to Reproduce

1. adc sync -f config.yaml --label-selector  deployment=staging    with  config.yaml

```yaml
services:
  - name: mockbin Service
    labels:
      deployment: staging
    upstream:
      name: Default Upstream
      scheme: http
      type: roundrobin
      hash_on: vars
      nodes:
        - host: mock.api7.ai
          port: 80
          weight: 100
          priority: 0
      timeout:
        connect: 60
        send: 60
        read: 60
      retry_timeout: 0
      keepalive_pool:
        size: 320
        idle_timeout: 60
        requests: 1000
      pass_host: pass
    strip_path_prefix: true
```

### Environment

- APISIX version: 3.9.0
- ADC version (run `adc version`):0.19.0
- Operating system (run `uname -a`): kubernetes
