### ISSUE TITLE
How to link Route and Upstream?

### ISSUE THREAD

**Issue by illia-weisser** [api7/adc#268]
I don't understand how to tell Route which Upstream to use

**Comment by bzp2010** [comment]
In short, this is not possible. The upstream must be added to the route via service.

```yaml
services:
  - name: demo
    upstream:
      nodes:
        host: 1.1.1.1
        port: 443
        weight: 100
    plugins:
      key-auth: {}
    routes:
      - name: demo-1
         uris: [/*]
         plugins: {}

```

ADC now does not support referenced upstreams (via upstream_id, they must be inlined to the service, use YAML anchor syntax if you need to reuse them).
It also does not support standalone routes that are not part of a service (routes must be associated with a service).
