### ISSUE TITLE
Docs: How to create `upstream` object with `adc`

### ISSUE THREAD

**Issue by davidlukac-wisi** [api7/adc#63]
### Current State

I found some example `config.yaml` for creating `routes` and `services` in `/adc.yaml` file in repo root as well as here https://api7.ai/blog/managing-apisix-declaratively , but not for creating `upstream` objects separately. Is it just not documented, or does `adc` not have capability to create `upstream` objects at the moment?

### Desired State

Documentation should contain an example for creation of each object type.

**Comment by pottekkat** [comment]
You can create upstream objects directly without the service abstraction with configurations like the one shown below:

```yaml
name: "Upstream and route configuration"
version: "1.0.0"
routes:
  - name: httpbin-route
    uri: "/anything"
    methods:
      - GET
    upstream:
      name: httpbin-upstream
      id: 1
      nodes:
        - host: httpbin.org
          port: 80
          weight: 1
```

We should definitely look into how we can document this better and in a more intuitive fashion. But in general, there should be parity (ideally) between the usual APISIX configuration and the declarative configuration in ADC.
